### ISSUE TITLE
Validation should use something other than props to pass down validation functions

### ISSUE THREAD

**Issue by emgage** [emgage/engage-ui#2]
Currently we are using props to send rc-form props. As a result, we have to change FormGroup, Item, and possibly other components.  We need to look into an alternative, like context.  I have not been able to get context to work.

Commit: https://github.com/emgage/engage-ui/commit/2853a05f8cfec113a333b4e85768729e3f0e2def

**Comment by harsimranb** [comment]
Resolving using React 16 Context
